//
//  INS3DPlanetGenerator.h
//  INSCoreMedia
//
//  Created by HFY on 2018/12/18.
//  Copyright © 2018年 insta360. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, INS3DPlanetGeneratorError) {
    INS3DPlanetGeneratorErrorROIImage,
    INS3DPlanetGeneratorErrorBodyMask,
    INS3DPlanetGeneratorErrorSVMSky,
    INS3DPlanetGeneratorErrorDisparity,
    INS3DPlanetGeneratorErrorPanoToPlanet,
    INS3DPlanetGeneratorErrorVirtualView,
    INS3DPlanetGeneratorErrorProcessList,
    INS3DPlanetGeneratorErrorEncodeJpeg,
    
};

@interface INS3DPlanetConfiguration : NSObject

//if nil, the generator will return nil for imageList and encodeJpegData
@property (nullable, nonatomic) UIImage *bodyMask;

//if nil, the generator will return nil for imageList and encodeJpegData
@property (nullable, nonatomic) UIImage *skyMask;

//should no if bodyMask state is 0.
@property (nonatomic) BOOL isHaveBody;

//should no if skyMask state is 0.
@property (nonatomic) BOOL isHaveSky;

//body disparity value
@property (nonatomic) uint8_t bodyDispVal;

//sky disparity value
@property (nonatomic) uint8_t skyDispVal;

//the encode JPEG image is generated by source image and disparity image. this parameter indicates the size  of JPEG image. 1:1(800,800) 3:4(720,960) 9:16(540, 960) 4:3(960,720) 16:9(960,540)
@property (nonatomic) CGSize outPlanetSize;

//the image size in list
@property (nonatomic) CGSize outputSize;

//the encode JPEG image quality.0(worst)~100(best)
@property (nonatomic) int encodeQuality;

//the encode JPEG image meta, could be nil, or others you want to mark the image.
@property (nullable, nonatomic) NSString *encodeMeta;

//set YES if you want to set a logo.
@property (nonatomic) BOOL enableLogo;

//the logo image. If you set enableLogo to YES, you should set this param a value not nil, otherwise, you will get an error. If enableLofo is NO, then you can give it a value or not.
@property (nullable, nonatomic) UIImage *logo;

@end


@interface INS3DPlanetGenerator : NSObject

@property (nonatomic, readonly) UIImage *sourceImage;


/**
 初始化·

 @param sourceImage 原图
 @return instance
 */
- (instancetype)initWithSourceImage:(UIImage *)sourceImage;


/**
 body roi rgb image, push this to face++ and get the second roiMask. If there is no face detected in face++, maybe it will return an image with black color, you still need to pass this image as roughMask parameter.

 @param roughMask from face++ first time detection.
 @return  roi info - {"roi_state":state, @"roi_image":image}. `state` is NSNumber which -1(no roi), 0 (have roi). `image` is UIImage.
 */
- (nullable NSDictionary *)roiImageWithRoughMask:(UIImage *)roughMask
                             error:(NSError * _Nullable * _Nullable)errorPtr;;


/**
 real body mask. If you get -1 during roi detection, you don't need to call this method.

 @param roughMask face++ first time detection
 @param roiMask face++ second time detection
 @return real body roi mask image
 */
- (nullable UIImage *)bodyMaskWithRoughMask:(UIImage *)roughMask roiMask:(UIImage *)roiMask
                             error:(NSError * _Nullable * _Nullable)errorPtr;

/**
 sky mask. Normally, whether there is an sky area detected, it has a return value. But it will return nil if can't find svm module and the source is gray colorspace.

 @param svmPath path for svm module
 @param errorPtr nil if there is no error occur.
 @return sky mask info - {"sky_state":state, @"sky_image":image}. `state` is NSNumber which -1(no sky), 0 (have sky). `image` is UIImage.
 */
- (nullable NSDictionary *)skyMaskWithSVMPath:(NSString *)svmPath
                          error:(NSError * _Nullable * _Nullable)errorPtr;




/**
 generate deptp imagelist and jpeg data with depth info. If you get -1 during roi detection, you don't need to call [bodyMaskWithRoughMask:roiMask:error:], just set the INS3DPlanetConfiguration correctly:isHaveBody = NO and bodyMask=roughMask.

 @param config configuration.
 @param complete complete block.
 */
- (void)generate3DPlanetWithConfiguration:(INS3DPlanetConfiguration *)config complete:(nullable void (^)(NSError  * _Nullable error,  NSArray<UIImage *>  * _Nullable imageList, NSData * _Nullable encodeJpegData))complete;


@end

NS_ASSUME_NONNULL_END
